# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'HappyBaby' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
    pod 'AFNetworking'
    pod 'Masonry'
    pod 'MJExtension'
    pod 'SDWebImage'
    pod 'WechatOpenSDK'
    pod 'IQKeyboardManager'
    pod 'MJRefresh'
    pod 'FMDB'
    pod 'MBProgressHUD'
  # Pods for BaseProj

  target 'HappyBabyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HappyBabyUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
